/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectSleeperRouteImport } from './routes/connect-sleeper'
import { Route as LeagueLeagueIdRouteRouteImport } from './routes/league/$leagueId/route'
import { Route as LeagueLeagueIdIndexRouteImport } from './routes/league/$leagueId/index'
import { Route as LeagueLeagueIdFreeAgentsRouteImport } from './routes/league/$leagueId/freeAgents'
import { Route as LeagueLeagueIdPlayersRouteImport } from './routes/league/$leagueId/players'
import { Route as LeagueLeagueIdTradeRouteImport } from './routes/league/$leagueId/trade'
import { Route as LeagueLeagueIdTeamsTeamIdRouteImport } from './routes/league/$leagueId/teams/$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSleeperRoute = ConnectSleeperRouteImport.update({
  id: '/connect-sleeper',
  path: '/connect-sleeper',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRouteRoute = LeagueLeagueIdRouteRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdIndexRoute = LeagueLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdFreeAgentsRoute =
  LeagueLeagueIdFreeAgentsRouteImport.update({
    id: '/freeAgents',
    path: '/freeAgents',
    getParentRoute: () => LeagueLeagueIdRouteRoute,
  } as any)
const LeagueLeagueIdPlayersRoute = LeagueLeagueIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdTradeRoute = LeagueLeagueIdTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdTeamsTeamIdRoute =
  LeagueLeagueIdTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => LeagueLeagueIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteRouteWithChildren
  '/league/$leagueId/freeAgents': typeof LeagueLeagueIdFreeAgentsRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/trade': typeof LeagueLeagueIdTradeRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/teams/$teamId': typeof LeagueLeagueIdTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/league/$leagueId/freeAgents': typeof LeagueLeagueIdFreeAgentsRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/trade': typeof LeagueLeagueIdTradeRoute
  '/league/$leagueId': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/teams/$teamId': typeof LeagueLeagueIdTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteRouteWithChildren
  '/league/$leagueId/freeAgents': typeof LeagueLeagueIdFreeAgentsRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/trade': typeof LeagueLeagueIdTradeRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/teams/$teamId': typeof LeagueLeagueIdTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-sleeper'
    | '/league/$leagueId'
    | '/league/$leagueId/freeAgents'
    | '/league/$leagueId/players'
    | '/league/$leagueId/trade'
    | '/league/$leagueId/'
    | '/league/$leagueId/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-sleeper'
    | '/league/$leagueId/freeAgents'
    | '/league/$leagueId/players'
    | '/league/$leagueId/trade'
    | '/league/$leagueId'
    | '/league/$leagueId/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/connect-sleeper'
    | '/league/$leagueId'
    | '/league/$leagueId/freeAgents'
    | '/league/$leagueId/players'
    | '/league/$leagueId/trade'
    | '/league/$leagueId/'
    | '/league/$leagueId/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectSleeperRoute: typeof ConnectSleeperRoute
  LeagueLeagueIdRouteRoute: typeof LeagueLeagueIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-sleeper': {
      id: '/connect-sleeper'
      path: '/connect-sleeper'
      fullPath: '/connect-sleeper'
      preLoaderRoute: typeof ConnectSleeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/': {
      id: '/league/$leagueId/'
      path: '/'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof LeagueLeagueIdIndexRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/freeAgents': {
      id: '/league/$leagueId/freeAgents'
      path: '/freeAgents'
      fullPath: '/league/$leagueId/freeAgents'
      preLoaderRoute: typeof LeagueLeagueIdFreeAgentsRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/players': {
      id: '/league/$leagueId/players'
      path: '/players'
      fullPath: '/league/$leagueId/players'
      preLoaderRoute: typeof LeagueLeagueIdPlayersRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/trade': {
      id: '/league/$leagueId/trade'
      path: '/trade'
      fullPath: '/league/$leagueId/trade'
      preLoaderRoute: typeof LeagueLeagueIdTradeRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/teams/$teamId': {
      id: '/league/$leagueId/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/league/$leagueId/teams/$teamId'
      preLoaderRoute: typeof LeagueLeagueIdTeamsTeamIdRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
  }
}

interface LeagueLeagueIdRouteRouteChildren {
  LeagueLeagueIdFreeAgentsRoute: typeof LeagueLeagueIdFreeAgentsRoute
  LeagueLeagueIdPlayersRoute: typeof LeagueLeagueIdPlayersRoute
  LeagueLeagueIdTradeRoute: typeof LeagueLeagueIdTradeRoute
  LeagueLeagueIdIndexRoute: typeof LeagueLeagueIdIndexRoute
  LeagueLeagueIdTeamsTeamIdRoute: typeof LeagueLeagueIdTeamsTeamIdRoute
}

const LeagueLeagueIdRouteRouteChildren: LeagueLeagueIdRouteRouteChildren = {
  LeagueLeagueIdFreeAgentsRoute: LeagueLeagueIdFreeAgentsRoute,
  LeagueLeagueIdPlayersRoute: LeagueLeagueIdPlayersRoute,
  LeagueLeagueIdTradeRoute: LeagueLeagueIdTradeRoute,
  LeagueLeagueIdIndexRoute: LeagueLeagueIdIndexRoute,
  LeagueLeagueIdTeamsTeamIdRoute: LeagueLeagueIdTeamsTeamIdRoute,
}

const LeagueLeagueIdRouteRouteWithChildren =
  LeagueLeagueIdRouteRoute._addFileChildren(LeagueLeagueIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectSleeperRoute: ConnectSleeperRoute,
  LeagueLeagueIdRouteRoute: LeagueLeagueIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
