/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminDataRouteImport } from './routes/admin-data'
import { Route as ConnectSleeperRouteImport } from './routes/connect-sleeper'
import { Route as ConnectYahooRouteImport } from './routes/connect-yahoo'
import { Route as LeagueLeagueIdRouteRouteImport } from './routes/league/$leagueId/route'
import { Route as LeagueLeagueIdIndexRouteImport } from './routes/league/$leagueId/index'
import { Route as LeagueLeagueIdCardsRouteImport } from './routes/league/$leagueId/cards'
import { Route as LeagueLeagueIdDepthChartsRouteImport } from './routes/league/$leagueId/depthCharts'
import { Route as LeagueLeagueIdFreeAgentsRouteImport } from './routes/league/$leagueId/freeAgents'
import { Route as LeagueLeagueIdInjuriesRouteImport } from './routes/league/$leagueId/injuries'
import { Route as LeagueLeagueIdMatchupRouteImport } from './routes/league/$leagueId/matchup'
import { Route as LeagueLeagueIdPlayersRouteImport } from './routes/league/$leagueId/players'
import { Route as LeagueLeagueIdTradeRouteImport } from './routes/league/$leagueId/trade'
import { Route as LeagueLeagueIdTeamsTeamIdRouteImport } from './routes/league/$leagueId/teams/$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin-data',
  path: '/admin-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSleeperRoute = ConnectSleeperRouteImport.update({
  id: '/connect-sleeper',
  path: '/connect-sleeper',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectYahooRoute = ConnectYahooRouteImport.update({
  id: '/connect-yahoo',
  path: '/connect-yahoo',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRouteRoute = LeagueLeagueIdRouteRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdIndexRoute = LeagueLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdCardsRoute = LeagueLeagueIdCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdDepthChartsRoute =
  LeagueLeagueIdDepthChartsRouteImport.update({
    id: '/depthCharts',
    path: '/depthCharts',
    getParentRoute: () => LeagueLeagueIdRouteRoute,
  } as any)
const LeagueLeagueIdFreeAgentsRoute =
  LeagueLeagueIdFreeAgentsRouteImport.update({
    id: '/freeAgents',
    path: '/freeAgents',
    getParentRoute: () => LeagueLeagueIdRouteRoute,
  } as any)
const LeagueLeagueIdInjuriesRoute = LeagueLeagueIdInjuriesRouteImport.update({
  id: '/injuries',
  path: '/injuries',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdMatchupRoute = LeagueLeagueIdMatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdPlayersRoute = LeagueLeagueIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdTradeRoute = LeagueLeagueIdTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdTeamsTeamIdRoute =
  LeagueLeagueIdTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => LeagueLeagueIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/connect-yahoo': typeof ConnectYahooRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteRouteWithChildren
  '/league/$leagueId/cards': typeof LeagueLeagueIdCardsRoute
  '/league/$leagueId/depthCharts': typeof LeagueLeagueIdDepthChartsRoute
  '/league/$leagueId/freeAgents': typeof LeagueLeagueIdFreeAgentsRoute
  '/league/$leagueId/injuries': typeof LeagueLeagueIdInjuriesRoute
  '/league/$leagueId/matchup': typeof LeagueLeagueIdMatchupRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/trade': typeof LeagueLeagueIdTradeRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/teams/$teamId': typeof LeagueLeagueIdTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/connect-yahoo': typeof ConnectYahooRoute
  '/league/$leagueId/cards': typeof LeagueLeagueIdCardsRoute
  '/league/$leagueId/depthCharts': typeof LeagueLeagueIdDepthChartsRoute
  '/league/$leagueId/freeAgents': typeof LeagueLeagueIdFreeAgentsRoute
  '/league/$leagueId/injuries': typeof LeagueLeagueIdInjuriesRoute
  '/league/$leagueId/matchup': typeof LeagueLeagueIdMatchupRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/trade': typeof LeagueLeagueIdTradeRoute
  '/league/$leagueId': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/teams/$teamId': typeof LeagueLeagueIdTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/connect-yahoo': typeof ConnectYahooRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteRouteWithChildren
  '/league/$leagueId/cards': typeof LeagueLeagueIdCardsRoute
  '/league/$leagueId/depthCharts': typeof LeagueLeagueIdDepthChartsRoute
  '/league/$leagueId/freeAgents': typeof LeagueLeagueIdFreeAgentsRoute
  '/league/$leagueId/injuries': typeof LeagueLeagueIdInjuriesRoute
  '/league/$leagueId/matchup': typeof LeagueLeagueIdMatchupRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/trade': typeof LeagueLeagueIdTradeRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/teams/$teamId': typeof LeagueLeagueIdTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-data'
    | '/connect-sleeper'
    | '/connect-yahoo'
    | '/league/$leagueId'
    | '/league/$leagueId/cards'
    | '/league/$leagueId/depthCharts'
    | '/league/$leagueId/freeAgents'
    | '/league/$leagueId/injuries'
    | '/league/$leagueId/matchup'
    | '/league/$leagueId/players'
    | '/league/$leagueId/trade'
    | '/league/$leagueId/'
    | '/league/$leagueId/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-data'
    | '/connect-sleeper'
    | '/connect-yahoo'
    | '/league/$leagueId/cards'
    | '/league/$leagueId/depthCharts'
    | '/league/$leagueId/freeAgents'
    | '/league/$leagueId/injuries'
    | '/league/$leagueId/matchup'
    | '/league/$leagueId/players'
    | '/league/$leagueId/trade'
    | '/league/$leagueId'
    | '/league/$leagueId/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-data'
    | '/connect-sleeper'
    | '/connect-yahoo'
    | '/league/$leagueId'
    | '/league/$leagueId/cards'
    | '/league/$leagueId/depthCharts'
    | '/league/$leagueId/freeAgents'
    | '/league/$leagueId/injuries'
    | '/league/$leagueId/matchup'
    | '/league/$leagueId/players'
    | '/league/$leagueId/trade'
    | '/league/$leagueId/'
    | '/league/$leagueId/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminDataRoute: typeof AdminDataRoute
  ConnectSleeperRoute: typeof ConnectSleeperRoute
  ConnectYahooRoute: typeof ConnectYahooRoute
  LeagueLeagueIdRouteRoute: typeof LeagueLeagueIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-data': {
      id: '/admin-data'
      path: '/admin-data'
      fullPath: '/admin-data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-sleeper': {
      id: '/connect-sleeper'
      path: '/connect-sleeper'
      fullPath: '/connect-sleeper'
      preLoaderRoute: typeof ConnectSleeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-yahoo': {
      id: '/connect-yahoo'
      path: '/connect-yahoo'
      fullPath: '/connect-yahoo'
      preLoaderRoute: typeof ConnectYahooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/': {
      id: '/league/$leagueId/'
      path: '/'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof LeagueLeagueIdIndexRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/cards': {
      id: '/league/$leagueId/cards'
      path: '/cards'
      fullPath: '/league/$leagueId/cards'
      preLoaderRoute: typeof LeagueLeagueIdCardsRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/depthCharts': {
      id: '/league/$leagueId/depthCharts'
      path: '/depthCharts'
      fullPath: '/league/$leagueId/depthCharts'
      preLoaderRoute: typeof LeagueLeagueIdDepthChartsRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/freeAgents': {
      id: '/league/$leagueId/freeAgents'
      path: '/freeAgents'
      fullPath: '/league/$leagueId/freeAgents'
      preLoaderRoute: typeof LeagueLeagueIdFreeAgentsRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/injuries': {
      id: '/league/$leagueId/injuries'
      path: '/injuries'
      fullPath: '/league/$leagueId/injuries'
      preLoaderRoute: typeof LeagueLeagueIdInjuriesRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/matchup': {
      id: '/league/$leagueId/matchup'
      path: '/matchup'
      fullPath: '/league/$leagueId/matchup'
      preLoaderRoute: typeof LeagueLeagueIdMatchupRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/players': {
      id: '/league/$leagueId/players'
      path: '/players'
      fullPath: '/league/$leagueId/players'
      preLoaderRoute: typeof LeagueLeagueIdPlayersRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/trade': {
      id: '/league/$leagueId/trade'
      path: '/trade'
      fullPath: '/league/$leagueId/trade'
      preLoaderRoute: typeof LeagueLeagueIdTradeRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/teams/$teamId': {
      id: '/league/$leagueId/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/league/$leagueId/teams/$teamId'
      preLoaderRoute: typeof LeagueLeagueIdTeamsTeamIdRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
  }
}

interface LeagueLeagueIdRouteRouteChildren {
  LeagueLeagueIdCardsRoute: typeof LeagueLeagueIdCardsRoute
  LeagueLeagueIdDepthChartsRoute: typeof LeagueLeagueIdDepthChartsRoute
  LeagueLeagueIdFreeAgentsRoute: typeof LeagueLeagueIdFreeAgentsRoute
  LeagueLeagueIdInjuriesRoute: typeof LeagueLeagueIdInjuriesRoute
  LeagueLeagueIdMatchupRoute: typeof LeagueLeagueIdMatchupRoute
  LeagueLeagueIdPlayersRoute: typeof LeagueLeagueIdPlayersRoute
  LeagueLeagueIdTradeRoute: typeof LeagueLeagueIdTradeRoute
  LeagueLeagueIdIndexRoute: typeof LeagueLeagueIdIndexRoute
  LeagueLeagueIdTeamsTeamIdRoute: typeof LeagueLeagueIdTeamsTeamIdRoute
}

const LeagueLeagueIdRouteRouteChildren: LeagueLeagueIdRouteRouteChildren = {
  LeagueLeagueIdCardsRoute: LeagueLeagueIdCardsRoute,
  LeagueLeagueIdDepthChartsRoute: LeagueLeagueIdDepthChartsRoute,
  LeagueLeagueIdFreeAgentsRoute: LeagueLeagueIdFreeAgentsRoute,
  LeagueLeagueIdInjuriesRoute: LeagueLeagueIdInjuriesRoute,
  LeagueLeagueIdMatchupRoute: LeagueLeagueIdMatchupRoute,
  LeagueLeagueIdPlayersRoute: LeagueLeagueIdPlayersRoute,
  LeagueLeagueIdTradeRoute: LeagueLeagueIdTradeRoute,
  LeagueLeagueIdIndexRoute: LeagueLeagueIdIndexRoute,
  LeagueLeagueIdTeamsTeamIdRoute: LeagueLeagueIdTeamsTeamIdRoute,
}

const LeagueLeagueIdRouteRouteWithChildren =
  LeagueLeagueIdRouteRoute._addFileChildren(LeagueLeagueIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminDataRoute: AdminDataRoute,
  ConnectSleeperRoute: ConnectSleeperRoute,
  ConnectYahooRoute: ConnectYahooRoute,
  LeagueLeagueIdRouteRoute: LeagueLeagueIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
