/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminDataRouteImport } from './routes/admin-data'
import { Route as ConnectSleeperRouteImport } from './routes/connect-sleeper'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as LeagueLeagueIdRouteRouteImport } from './routes/league/$leagueId/route'
import { Route as LeagueLeagueIdIndexRouteImport } from './routes/league/$leagueId/index'
import { Route as LeagueLeagueIdMyBidsRouteImport } from './routes/league/$leagueId/myBids'
import { Route as LeagueLeagueIdPlayersRouteImport } from './routes/league/$leagueId/players'
import { Route as LeagueLeagueIdResultsRouteImport } from './routes/league/$leagueId/results'
import { Route as LeagueLeagueIdSettingsRouteImport } from './routes/league/$leagueId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin-data',
  path: '/admin-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSleeperRoute = ConnectSleeperRouteImport.update({
  id: '/connect-sleeper',
  path: '/connect-sleeper',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRouteRoute = LeagueLeagueIdRouteRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdIndexRoute = LeagueLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdMyBidsRoute = LeagueLeagueIdMyBidsRouteImport.update({
  id: '/myBids',
  path: '/myBids',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdPlayersRoute = LeagueLeagueIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdResultsRoute = LeagueLeagueIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdSettingsRoute = LeagueLeagueIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/league/$leagueId/myBids': typeof LeagueLeagueIdMyBidsRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/results': typeof LeagueLeagueIdResultsRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/join/$token': typeof JoinTokenRoute
  '/league/$leagueId/myBids': typeof LeagueLeagueIdMyBidsRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/results': typeof LeagueLeagueIdResultsRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/league/$leagueId': typeof LeagueLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/league/$leagueId/myBids': typeof LeagueLeagueIdMyBidsRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/results': typeof LeagueLeagueIdResultsRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-data'
    | '/connect-sleeper'
    | '/league/$leagueId'
    | '/join/$token'
    | '/league/$leagueId/myBids'
    | '/league/$leagueId/players'
    | '/league/$leagueId/results'
    | '/league/$leagueId/settings'
    | '/league/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-data'
    | '/connect-sleeper'
    | '/join/$token'
    | '/league/$leagueId/myBids'
    | '/league/$leagueId/players'
    | '/league/$leagueId/results'
    | '/league/$leagueId/settings'
    | '/league/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-data'
    | '/connect-sleeper'
    | '/league/$leagueId'
    | '/join/$token'
    | '/league/$leagueId/myBids'
    | '/league/$leagueId/players'
    | '/league/$leagueId/results'
    | '/league/$leagueId/settings'
    | '/league/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminDataRoute: typeof AdminDataRoute
  ConnectSleeperRoute: typeof ConnectSleeperRoute
  LeagueLeagueIdRouteRoute: typeof LeagueLeagueIdRouteRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-data': {
      id: '/admin-data'
      path: '/admin-data'
      fullPath: '/admin-data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-sleeper': {
      id: '/connect-sleeper'
      path: '/connect-sleeper'
      fullPath: '/connect-sleeper'
      preLoaderRoute: typeof ConnectSleeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/': {
      id: '/league/$leagueId/'
      path: '/'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof LeagueLeagueIdIndexRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/myBids': {
      id: '/league/$leagueId/myBids'
      path: '/myBids'
      fullPath: '/league/$leagueId/myBids'
      preLoaderRoute: typeof LeagueLeagueIdMyBidsRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/players': {
      id: '/league/$leagueId/players'
      path: '/players'
      fullPath: '/league/$leagueId/players'
      preLoaderRoute: typeof LeagueLeagueIdPlayersRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/results': {
      id: '/league/$leagueId/results'
      path: '/results'
      fullPath: '/league/$leagueId/results'
      preLoaderRoute: typeof LeagueLeagueIdResultsRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/settings': {
      id: '/league/$leagueId/settings'
      path: '/settings'
      fullPath: '/league/$leagueId/settings'
      preLoaderRoute: typeof LeagueLeagueIdSettingsRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
  }
}

interface LeagueLeagueIdRouteRouteChildren {
  LeagueLeagueIdMyBidsRoute: typeof LeagueLeagueIdMyBidsRoute
  LeagueLeagueIdPlayersRoute: typeof LeagueLeagueIdPlayersRoute
  LeagueLeagueIdResultsRoute: typeof LeagueLeagueIdResultsRoute
  LeagueLeagueIdSettingsRoute: typeof LeagueLeagueIdSettingsRoute
  LeagueLeagueIdIndexRoute: typeof LeagueLeagueIdIndexRoute
}

const LeagueLeagueIdRouteRouteChildren: LeagueLeagueIdRouteRouteChildren = {
  LeagueLeagueIdMyBidsRoute: LeagueLeagueIdMyBidsRoute,
  LeagueLeagueIdPlayersRoute: LeagueLeagueIdPlayersRoute,
  LeagueLeagueIdResultsRoute: LeagueLeagueIdResultsRoute,
  LeagueLeagueIdSettingsRoute: LeagueLeagueIdSettingsRoute,
  LeagueLeagueIdIndexRoute: LeagueLeagueIdIndexRoute,
}

const LeagueLeagueIdRouteRouteWithChildren =
  LeagueLeagueIdRouteRoute._addFileChildren(LeagueLeagueIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminDataRoute: AdminDataRoute,
  ConnectSleeperRoute: ConnectSleeperRoute,
  LeagueLeagueIdRouteRoute: LeagueLeagueIdRouteRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
