// Raw Sleeper stat keys (e.g. "rec_yd", "pts_allow_0") aren't readable as
// column headers - map the ones we've seen in real responses to plain
// labels, and fall back to title-casing anything unmapped (e.g. bonus/return
// fields) so a header never renders as a raw snake_case key.
export const STAT_LABELS: Record<string, string> = {
  rec: "Receptions",
  rec_yd: "Rec Yds",
  rec_td: "Rec TDs",
  rec_fd: "Rec First Downs",
  rec_tgt: "Targets",
  rec_2pt: "Rec 2-PT",
  rec_0_4: "Receptions (0-4 Yds)",
  rec_5_9: "Receptions (5-9 Yds)",
  rec_10_19: "Receptions (10-19 Yds)",
  rec_20_29: "Receptions (20-29 Yds)",
  rec_30_39: "Receptions (30-39 Yds)",
  rec_40p: "Receptions (40+ Yds)",
  rush_att: "Rush Att",
  rush_yd: "Rush Yds",
  rush_td: "Rush TDs",
  rush_fd: "Rush First Downs",
  rush_2pt: "Rush 2-PT",
  pass_att: "Pass Att",
  pass_cmp: "Completions",
  pass_yd: "Pass Yds",
  pass_td: "Pass TDs",
  pass_int: "Interceptions",
  pass_fd: "Pass First Downs",
  pass_2pt: "Pass 2-PT",
  fum: "Fumbles",
  fum_lost: "Fumbles Lost",
  gp: "Games Played",
  sack: "Sacks",
  int: "Interceptions",
  fum_rec: "Fumble Recoveries",
  blk_kick: "Blocked Kicks",
  def_fum_td: "Defensive Fumble TDs",
  def_kr_td: "Kick Return TDs",
  pts_allow_0: "Pts Allowed (0)",
  pts_allow_1_6: "Pts Allowed (1-6)",
  pts_allow_7_13: "Pts Allowed (7-13)",
  pts_allow_14_20: "Pts Allowed (14-20)",
  pts_allow_21_27: "Pts Allowed (21-27)",
  pts_allow_28_34: "Pts Allowed (28-34)",
  pts_allow_35p: "Pts Allowed (35+)",
  yds_allow_0_100: "Yds Allowed (0-100)",
  fgm_40_49: "FG Made (40-49)",
  fgm_50p: "FG Made (50+)",
  fgm_yds: "FG Yards",
  fgmiss_40_49: "FG Missed (40-49)",
  fgmiss_50p: "FG Missed (50+)",
  xpm: "XP Made",
  xpmiss: "XP Missed",
};
