/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminDataRouteImport } from './routes/admin-data'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BoardLeagueIdRouteImport } from './routes/board/$leagueId'
import { Route as LeagueLeagueIdRouteRouteImport } from './routes/league/$leagueId/route'
import { Route as ReportCardLeagueIdRouteImport } from './routes/reportCard/$leagueId'
import { Route as SeasonLeagueIdRouteRouteImport } from './routes/season/$leagueId/route'
import { Route as LeagueLeagueIdIndexRouteImport } from './routes/league/$leagueId/index'
import { Route as LeagueLeagueIdBudgetRouteImport } from './routes/league/$leagueId/budget'
import { Route as LeagueLeagueIdDraftRouteImport } from './routes/league/$leagueId/draft'
import { Route as LeagueLeagueIdInjuriesRouteImport } from './routes/league/$leagueId/injuries'
import { Route as LeagueLeagueIdKeepersRouteImport } from './routes/league/$leagueId/keepers'
import { Route as LeagueLeagueIdLeagueRouteImport } from './routes/league/$leagueId/league'
import { Route as LeagueLeagueIdMyTeamRouteImport } from './routes/league/$leagueId/myTeam'
import { Route as LeagueLeagueIdPlayersRouteImport } from './routes/league/$leagueId/players'
import { Route as LeagueLeagueIdSettingsRouteImport } from './routes/league/$leagueId/settings'
import { Route as SeasonLeagueIdIndexRouteImport } from './routes/season/$leagueId/index'
import { Route as SeasonLeagueIdSettingsRouteImport } from './routes/season/$leagueId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin-data',
  path: '/admin-data',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardLeagueIdRoute = BoardLeagueIdRouteImport.update({
  id: '/board/$leagueId',
  path: '/board/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRouteRoute = LeagueLeagueIdRouteRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCardLeagueIdRoute = ReportCardLeagueIdRouteImport.update({
  id: '/reportCard/$leagueId',
  path: '/reportCard/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonLeagueIdRouteRoute = SeasonLeagueIdRouteRouteImport.update({
  id: '/season/$leagueId',
  path: '/season/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdIndexRoute = LeagueLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdBudgetRoute = LeagueLeagueIdBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdDraftRoute = LeagueLeagueIdDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdInjuriesRoute = LeagueLeagueIdInjuriesRouteImport.update({
  id: '/injuries',
  path: '/injuries',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdKeepersRoute = LeagueLeagueIdKeepersRouteImport.update({
  id: '/keepers',
  path: '/keepers',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdLeagueRoute = LeagueLeagueIdLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdMyTeamRoute = LeagueLeagueIdMyTeamRouteImport.update({
  id: '/myTeam',
  path: '/myTeam',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdPlayersRoute = LeagueLeagueIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const LeagueLeagueIdSettingsRoute = LeagueLeagueIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LeagueLeagueIdRouteRoute,
} as any)
const SeasonLeagueIdIndexRoute = SeasonLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeasonLeagueIdRouteRoute,
} as any)
const SeasonLeagueIdSettingsRoute = SeasonLeagueIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SeasonLeagueIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/billing': typeof BillingRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteRouteWithChildren
  '/season/$leagueId': typeof SeasonLeagueIdRouteRouteWithChildren
  '/board/$leagueId': typeof BoardLeagueIdRoute
  '/reportCard/$leagueId': typeof ReportCardLeagueIdRoute
  '/league/$leagueId/budget': typeof LeagueLeagueIdBudgetRoute
  '/league/$leagueId/draft': typeof LeagueLeagueIdDraftRoute
  '/league/$leagueId/injuries': typeof LeagueLeagueIdInjuriesRoute
  '/league/$leagueId/keepers': typeof LeagueLeagueIdKeepersRoute
  '/league/$leagueId/league': typeof LeagueLeagueIdLeagueRoute
  '/league/$leagueId/myTeam': typeof LeagueLeagueIdMyTeamRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/season/$leagueId/settings': typeof SeasonLeagueIdSettingsRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/season/$leagueId/': typeof SeasonLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/billing': typeof BillingRoute
  '/board/$leagueId': typeof BoardLeagueIdRoute
  '/reportCard/$leagueId': typeof ReportCardLeagueIdRoute
  '/league/$leagueId/budget': typeof LeagueLeagueIdBudgetRoute
  '/league/$leagueId/draft': typeof LeagueLeagueIdDraftRoute
  '/league/$leagueId/injuries': typeof LeagueLeagueIdInjuriesRoute
  '/league/$leagueId/keepers': typeof LeagueLeagueIdKeepersRoute
  '/league/$leagueId/league': typeof LeagueLeagueIdLeagueRoute
  '/league/$leagueId/myTeam': typeof LeagueLeagueIdMyTeamRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/season/$leagueId/settings': typeof SeasonLeagueIdSettingsRoute
  '/league/$leagueId': typeof LeagueLeagueIdIndexRoute
  '/season/$leagueId': typeof SeasonLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/billing': typeof BillingRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteRouteWithChildren
  '/season/$leagueId': typeof SeasonLeagueIdRouteRouteWithChildren
  '/board/$leagueId': typeof BoardLeagueIdRoute
  '/reportCard/$leagueId': typeof ReportCardLeagueIdRoute
  '/league/$leagueId/budget': typeof LeagueLeagueIdBudgetRoute
  '/league/$leagueId/draft': typeof LeagueLeagueIdDraftRoute
  '/league/$leagueId/injuries': typeof LeagueLeagueIdInjuriesRoute
  '/league/$leagueId/keepers': typeof LeagueLeagueIdKeepersRoute
  '/league/$leagueId/league': typeof LeagueLeagueIdLeagueRoute
  '/league/$leagueId/myTeam': typeof LeagueLeagueIdMyTeamRoute
  '/league/$leagueId/players': typeof LeagueLeagueIdPlayersRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/season/$leagueId/settings': typeof SeasonLeagueIdSettingsRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/season/$leagueId/': typeof SeasonLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-data'
    | '/billing'
    | '/league/$leagueId'
    | '/season/$leagueId'
    | '/board/$leagueId'
    | '/reportCard/$leagueId'
    | '/league/$leagueId/budget'
    | '/league/$leagueId/draft'
    | '/league/$leagueId/injuries'
    | '/league/$leagueId/keepers'
    | '/league/$leagueId/league'
    | '/league/$leagueId/myTeam'
    | '/league/$leagueId/players'
    | '/league/$leagueId/settings'
    | '/season/$leagueId/settings'
    | '/league/$leagueId/'
    | '/season/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-data'
    | '/billing'
    | '/board/$leagueId'
    | '/reportCard/$leagueId'
    | '/league/$leagueId/budget'
    | '/league/$leagueId/draft'
    | '/league/$leagueId/injuries'
    | '/league/$leagueId/keepers'
    | '/league/$leagueId/league'
    | '/league/$leagueId/myTeam'
    | '/league/$leagueId/players'
    | '/league/$leagueId/settings'
    | '/season/$leagueId/settings'
    | '/league/$leagueId'
    | '/season/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-data'
    | '/billing'
    | '/league/$leagueId'
    | '/season/$leagueId'
    | '/board/$leagueId'
    | '/reportCard/$leagueId'
    | '/league/$leagueId/budget'
    | '/league/$leagueId/draft'
    | '/league/$leagueId/injuries'
    | '/league/$leagueId/keepers'
    | '/league/$leagueId/league'
    | '/league/$leagueId/myTeam'
    | '/league/$leagueId/players'
    | '/league/$leagueId/settings'
    | '/season/$leagueId/settings'
    | '/league/$leagueId/'
    | '/season/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminDataRoute: typeof AdminDataRoute
  BillingRoute: typeof BillingRoute
  LeagueLeagueIdRouteRoute: typeof LeagueLeagueIdRouteRouteWithChildren
  SeasonLeagueIdRouteRoute: typeof SeasonLeagueIdRouteRouteWithChildren
  BoardLeagueIdRoute: typeof BoardLeagueIdRoute
  ReportCardLeagueIdRoute: typeof ReportCardLeagueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-data': {
      id: '/admin-data'
      path: '/admin-data'
      fullPath: '/admin-data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$leagueId': {
      id: '/board/$leagueId'
      path: '/board/$leagueId'
      fullPath: '/board/$leagueId'
      preLoaderRoute: typeof BoardLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportCard/$leagueId': {
      id: '/reportCard/$leagueId'
      path: '/reportCard/$leagueId'
      fullPath: '/reportCard/$leagueId'
      preLoaderRoute: typeof ReportCardLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season/$leagueId': {
      id: '/season/$leagueId'
      path: '/season/$leagueId'
      fullPath: '/season/$leagueId'
      preLoaderRoute: typeof SeasonLeagueIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/': {
      id: '/league/$leagueId/'
      path: '/'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof LeagueLeagueIdIndexRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/budget': {
      id: '/league/$leagueId/budget'
      path: '/budget'
      fullPath: '/league/$leagueId/budget'
      preLoaderRoute: typeof LeagueLeagueIdBudgetRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/draft': {
      id: '/league/$leagueId/draft'
      path: '/draft'
      fullPath: '/league/$leagueId/draft'
      preLoaderRoute: typeof LeagueLeagueIdDraftRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/injuries': {
      id: '/league/$leagueId/injuries'
      path: '/injuries'
      fullPath: '/league/$leagueId/injuries'
      preLoaderRoute: typeof LeagueLeagueIdInjuriesRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/keepers': {
      id: '/league/$leagueId/keepers'
      path: '/keepers'
      fullPath: '/league/$leagueId/keepers'
      preLoaderRoute: typeof LeagueLeagueIdKeepersRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/league': {
      id: '/league/$leagueId/league'
      path: '/league'
      fullPath: '/league/$leagueId/league'
      preLoaderRoute: typeof LeagueLeagueIdLeagueRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/myTeam': {
      id: '/league/$leagueId/myTeam'
      path: '/myTeam'
      fullPath: '/league/$leagueId/myTeam'
      preLoaderRoute: typeof LeagueLeagueIdMyTeamRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/players': {
      id: '/league/$leagueId/players'
      path: '/players'
      fullPath: '/league/$leagueId/players'
      preLoaderRoute: typeof LeagueLeagueIdPlayersRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/league/$leagueId/settings': {
      id: '/league/$leagueId/settings'
      path: '/settings'
      fullPath: '/league/$leagueId/settings'
      preLoaderRoute: typeof LeagueLeagueIdSettingsRouteImport
      parentRoute: typeof LeagueLeagueIdRouteRoute
    }
    '/season/$leagueId/': {
      id: '/season/$leagueId/'
      path: '/'
      fullPath: '/season/$leagueId/'
      preLoaderRoute: typeof SeasonLeagueIdIndexRouteImport
      parentRoute: typeof SeasonLeagueIdRouteRoute
    }
    '/season/$leagueId/settings': {
      id: '/season/$leagueId/settings'
      path: '/settings'
      fullPath: '/season/$leagueId/settings'
      preLoaderRoute: typeof SeasonLeagueIdSettingsRouteImport
      parentRoute: typeof SeasonLeagueIdRouteRoute
    }
  }
}

interface LeagueLeagueIdRouteRouteChildren {
  LeagueLeagueIdBudgetRoute: typeof LeagueLeagueIdBudgetRoute
  LeagueLeagueIdDraftRoute: typeof LeagueLeagueIdDraftRoute
  LeagueLeagueIdInjuriesRoute: typeof LeagueLeagueIdInjuriesRoute
  LeagueLeagueIdKeepersRoute: typeof LeagueLeagueIdKeepersRoute
  LeagueLeagueIdLeagueRoute: typeof LeagueLeagueIdLeagueRoute
  LeagueLeagueIdMyTeamRoute: typeof LeagueLeagueIdMyTeamRoute
  LeagueLeagueIdPlayersRoute: typeof LeagueLeagueIdPlayersRoute
  LeagueLeagueIdSettingsRoute: typeof LeagueLeagueIdSettingsRoute
  LeagueLeagueIdIndexRoute: typeof LeagueLeagueIdIndexRoute
}

const LeagueLeagueIdRouteRouteChildren: LeagueLeagueIdRouteRouteChildren = {
  LeagueLeagueIdBudgetRoute: LeagueLeagueIdBudgetRoute,
  LeagueLeagueIdDraftRoute: LeagueLeagueIdDraftRoute,
  LeagueLeagueIdInjuriesRoute: LeagueLeagueIdInjuriesRoute,
  LeagueLeagueIdKeepersRoute: LeagueLeagueIdKeepersRoute,
  LeagueLeagueIdLeagueRoute: LeagueLeagueIdLeagueRoute,
  LeagueLeagueIdMyTeamRoute: LeagueLeagueIdMyTeamRoute,
  LeagueLeagueIdPlayersRoute: LeagueLeagueIdPlayersRoute,
  LeagueLeagueIdSettingsRoute: LeagueLeagueIdSettingsRoute,
  LeagueLeagueIdIndexRoute: LeagueLeagueIdIndexRoute,
}

const LeagueLeagueIdRouteRouteWithChildren =
  LeagueLeagueIdRouteRoute._addFileChildren(LeagueLeagueIdRouteRouteChildren)

interface SeasonLeagueIdRouteRouteChildren {
  SeasonLeagueIdSettingsRoute: typeof SeasonLeagueIdSettingsRoute
  SeasonLeagueIdIndexRoute: typeof SeasonLeagueIdIndexRoute
}

const SeasonLeagueIdRouteRouteChildren: SeasonLeagueIdRouteRouteChildren = {
  SeasonLeagueIdSettingsRoute: SeasonLeagueIdSettingsRoute,
  SeasonLeagueIdIndexRoute: SeasonLeagueIdIndexRoute,
}

const SeasonLeagueIdRouteRouteWithChildren =
  SeasonLeagueIdRouteRoute._addFileChildren(SeasonLeagueIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminDataRoute: AdminDataRoute,
  BillingRoute: BillingRoute,
  LeagueLeagueIdRouteRoute: LeagueLeagueIdRouteRouteWithChildren,
  SeasonLeagueIdRouteRoute: SeasonLeagueIdRouteRouteWithChildren,
  BoardLeagueIdRoute: BoardLeagueIdRoute,
  ReportCardLeagueIdRoute: ReportCardLeagueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
